CREATE TABLE IF NOT EXISTS 'User'
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  login VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS 'Chatroom'
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) UNIQUE NOT NULL,
  owner INT NOT NULL REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS 'Message'
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  author INT NOT NULL REFERENCES User(id),
  chatroom INT ON DELETE CASCADE REFERENCES Chatroom(id),
  text VARCHAR(255) NOT NULL,
  datetime TIMESTAMP NOT NULL
);
