CREATE TABLE IF NOT EXISTS User
(
  id SERIAL PRIMARY KEY,
  login VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Chatroom
(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  owner INT NOT NULL REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Message
(
  id SERIAL PRIMARY KEY,
  author INT NOT NULL REFERENCES User(id),
  chatroom INT REFERENCES Chatroom(id) ON DELETE CASCADE ,
  text VARCHAR(255) NOT NULL,
  datetime TIMESTAMP NOT NULL
);
